---
language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.0.5.0
  - jruby-9.1.7.0
  - jruby-head
  - rbx-2.71828182

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
